setwd("C:/Stage_Shanghai/Scripts")
mydata <- read.csv('improved_results2.csv',header=T,na.strings=c(""))
sapply(results.data.raw,function(x) sum(is.na(x)))
sapply(results.data.raw, function(x) sum(is.null(x)))
mydata$hydro_criteria <- factor(mydata$hydro_criteria)
mydata$green_criteria <- factor(mydata$green_criteria)
mydata$variable_y <- factor(mydata$variable_y)
mydata$normalized_aadt[is.na(mydata$normalized_aadt)] <- mean(mydata$normalized_aadt,na.rm=T)
mydata$normalized_aadt <- as.numeric(as.character(mydata$normalized_aadt))
summary(mydata$normalized_aadt)
boxplot(mydata$height_criteria~mydata$variable_y,xlab="Stress",ylab="Hauteur de bâti moyenne en feet dans un rayon de 100m",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données de la hauteur du bâti en fonction du stress")
boxplot(mydata$age_criteria~mydata$variable_y,xlab="Stress",ylab="Age de bâti moyen en années dans un rayon de 100m",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données de l'âge du bâti en fonction du stress")
boxplot(mydata$area_criteria~mydata$variable_y,xlab="Stress",ylab="Surface bâti en square feet dans un rayon de 100m (densité)",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données de la densité du bâti en fonction du stress")
boxplot(mydata$count_trees~mydata$variable_y,xlab="Stress",ylab="Nombre d'arbres",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données du nombre d'arbres en fonction du stress")
boxplot(mydata$count_cafes~mydata$variable_y,xlab="Stress",ylab="Nombre de cafés",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données du nombre de cafés en fonction du stress")
boxplot(mydata$count_benches~mydata$variable_y,xlab="Stress",ylab="Nombre de bancs publics",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données du nombre de bancs en fonction du stress")
boxplot(mydata$count_route_under_20~mydata$variable_y,xlab="Stress",ylab="Nb routes à moins de 20m",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données du nombre de routes à moins de 20m en fonction du stress")
boxplot(mydata$count_route_under_50~mydata$variable_y,xlab="Stress",ylab="Nb routes à moins de 50m",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données du nombre de routes à moins de 50m en fonction du stress")
boxplot(mydata$inverse_square_nearest_route~mydata$variable_y,xlab="Stress",ylab="1/d² (m-2)",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données de la distance au trafic en fonction du stress")
boxplot(mydata$inverse_square_intersecting_nearest_route~mydata$variable_y,xlab="Stress",ylab="1/d_inter²",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données de la distance au trafic indirect en fonction du stress")
boxplot(mydata$normalized_aadt~mydata$variable_y,xlab="Stress",ylab="volume de trafic normalisé",col=c("lightgreen","palevioletred1"), outline=FALSE, range=2, main="Analyse exploratoire des données du volume de trafic en fonction du stress")
