setwd("C:/Stage_Shanghai/Scripts")
results.data.raw <- read.csv('improved_results2.csv',header=T,na.strings=c("", "null"))
summary(results.data.raw)
sapply(results.data.raw,function(x) sum(is.na(x)))
sapply(results.data.raw, function(x) sum(is.null(x)))
library(Amelia)
missmap(results.data.raw, main = "Missing values vs observed")
mydata <- results.data.raw
mydata$hydro_criteria <- factor(mydata$hydro_criteria)
mydata$green_criteria <- factor(mydata$green_criteria)
mydata$variable_y <- factor(mydata$variable_y)
mydata$normalized_aadt <- as.numeric(as.character(mydata$normalized_aadt))
is.factor(mydata$normalized_aadt)
summary(mydata$normalized_aadt)
require(ggplot2)
qplot(mydata$normalized_aadt)
qplot(mydata$height_criteria)
model.omit <- glm( variable_y ~.,family=binomial(link='logit'),data=mydata, na.action = na.omit)
summary(model.omit)
library(pscl)
pR2(model.omit)
with(model.omit, null.deviance - deviance)
with(model.omit, df.null - df.residual)
with(model.omit, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))
logLik(model.omit)
#tidy_mylogit <- tidy(model)
#tidy_mylogit
#write.csv(tidy_mylogit, "improved_results_regression.csv")